sonar.projectKey=notely
sonar.projectName=Notely
sonar.sourceEncoding=UTF-8

sonar.sources=backend,frontend/src
sonar.tests=backend/test,frontend/src
sonar.test.inclusions=**/*.test.js,**/*.test.jsx

sonar.exclusions=**/node_modules/**,**/coverage/**,**/dist/**,**/assets/**,**/*.test.js,**/*.test.jsx,**/__mocks__/**

sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info,frontend/coverage/lcov.info

sonar.javascript.node.maxspace=1024
